# Generated by Django 4.1.5 on 2023-09-07 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='customers/profiles/avatars/default-profile-picture.png', upload_to='customers/profiles/avatars/')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Other'), (4, 'Preferred not to say')], null=True)),
                ('education', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Under Graduate'), (2, 'Post Graduates'), (3, 'Vocational'), (4, 'Higher Secondary Education'), (5, 'Secondary Education'), (6, 'Elementary Education')], null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.PositiveBigIntegerField(blank=True, choices=[(1, '(UT6) Andaman and Nicobar Islands'), (2, '(S10) Andhra Pradesh'), (3, '(S26) Arunachal Pradesh'), (4, '(S15) Assam'), (5, '(S3) Bihar'), (6, '(UT4) Chandigarh'), (7, '(S17) Chhattisgarh'), (8, '(UT5) Dadra and Nagar Haveli and Daman and Diu'), (9, '(S25) Goa'), (10, '(S9) Gujarat'), (11, '(S18) Haryana'), (12, '(S20) Himachal Pradesh'), (13, '(UT2) Jammu and Kashmir'), (14, '(S14) Jharkhand'), (15, '(S8) Karnataka'), (16, '(S13) Kerala'), (17, '(UT7) Ladakh'), (18, '(UT8) Lakshadweep'), (19, '(UT8) Madhya Pradesh'), (20, '(S2) Maharashtra'), (21, '(S23) Manipur'), (22, '(S22) Meghalaya'), (23, '(S22) Mizoram'), (24, '(S24) Nagaland'), (25, '(UT1) New Delhi'), (26, '(S11) Odisha'), (27, '(UT3) Puducherry'), (28, '(S16) Punjab'), (29, '(S7) Rajasthan'), (30, '(S28) Sikkim'), (31, '(S6) Tamil Nadu'), (32, '(S12) Telangana'), (33, '(S21) Tripura'), (34, '(S1) Uttar Pradesh'), (35, '(S) Uttarakhand'), (36, '(S4) West Bengal')], null=True)),
                ('country', models.PositiveBigIntegerField(blank=True, choices=[(78, 'India'), (1, 'Afghanistan'), (2, 'Albania'), (3, 'Algeria'), (4, 'Andorra'), (5, 'Angola'), (6, 'Antigua and Barbuda'), (7, 'Argentina'), (8, 'Armenia'), (9, 'Australia'), (10, 'Austria'), (11, 'Azerbaijan'), (12, 'Bahamas'), (13, 'Bahrain'), (14, 'Bangladesh'), (15, 'Barbados'), (16, 'Belarus'), (17, 'Belgium'), (18, 'Belize'), (19, 'Benin'), (20, 'Bhutan'), (21, 'Bolivia'), (22, 'Bosnia and Herzegovina'), (23, 'Botswana'), (24, 'Brazil'), (25, 'Brunei'), (26, 'Bulgaria'), (27, 'Burkina Faso'), (28, 'Burundi'), (29, "Cote d'Ivoire'"), (30, 'Cabo Verde'), (31, 'Cambodia'), (32, 'Cameroon'), (33, 'Canada'), (34, 'Central African Republic'), (35, 'Chad'), (36, 'Chile'), (37, 'China'), (38, 'Colombia'), (39, 'Comoros'), (40, 'Congo (Congo-Brazzaville)'), (41, 'Costa Rica'), (42, 'Croatia'), (43, 'Cuba'), (44, 'Cyprus'), (45, 'Czechia (Czech Republic)'), (46, 'Democratic Republic of the Congo'), (47, 'Denmark'), (48, 'Djibouti'), (49, 'Dominica'), (50, 'Dominican Republic'), (51, 'Ecuador'), (52, 'Egypt'), (53, 'El Salvador'), (54, 'Equatorial Guinea'), (55, 'Eritrea'), (56, 'Estonia'), (57, 'Eswatini (fmr. "Swaziland")'), (58, 'Ethiopia'), (59, 'Fiji'), (60, 'Finland'), (61, 'France'), (62, 'Gabon'), (63, 'Gambia'), (64, 'Georgia'), (65, 'Germany'), (66, 'Ghana'), (67, 'Greece'), (68, 'Grenada'), (69, 'Guatemala'), (70, 'Guinea'), (71, 'Guinea-Bissau'), (72, 'Guyana'), (73, 'Haiti'), (74, 'Holy See'), (75, 'Honduras'), (76, 'Hungary'), (77, 'Iceland'), (79, 'Indonesia'), (80, 'Iran'), (81, 'Iraq'), (82, 'Ireland'), (83, 'Israel'), (84, 'Italy'), (85, 'Jamaica'), (86, 'Japan'), (87, 'Jordan'), (88, 'Kazakhstan'), (89, 'Kenya'), (90, 'Kiribati'), (91, 'Kuwait'), (92, 'Kyrgyzstan'), (93, 'Laos'), (94, 'Latvia'), (95, 'Lebanon'), (96, 'Lesotho'), (97, 'Liberia'), (98, 'Libya'), (99, 'Liechtenstein'), (100, 'Lithuania'), (101, 'Luxembourg'), (102, 'Madagascar'), (103, 'Malawi'), (104, 'Malaysia'), (105, 'Maldives'), (106, 'Mali'), (107, 'Malta'), (108, 'Marshall Islands'), (109, 'Mauritania'), (110, 'Mauritius'), (111, 'Mexico'), (112, 'Micronesia'), (113, 'Moldova'), (114, 'Monaco'), (115, 'Mongolia'), (116, 'Montenegro'), (117, 'Morocco'), (118, 'Mozambique'), (119, 'Myanmar (formerly Burma)'), (120, 'Namibia'), (121, 'Nauru'), (122, 'Nepal'), (123, 'Netherlands'), (124, 'New Zealand'), (125, 'Nicaragua'), (126, 'Niger'), (127, 'Nigeria'), (128, 'North Korea'), (129, 'North Macedonia'), (130, 'Norway'), (131, 'Oman'), (132, 'Pakistan'), (133, 'Palau'), (134, 'Palestine State'), (135, 'Panama'), (136, 'Papua New Guinea'), (137, 'Paraguay'), (138, 'Peru'), (139, 'Philippines'), (140, 'Poland'), (141, 'Portugal'), (142, 'Qatar'), (143, 'Romania'), (144, 'Russia'), (145, 'Rwanda'), (146, 'Saint Kitts and Nevis'), (147, 'Saint Lucia'), (148, 'Saint Vincent and the Grenadines'), (149, 'Samoa'), (150, 'San Marino'), (151, 'Sao Tome and Principe'), (152, 'Saudi Arabia'), (153, 'Senegal'), (154, 'Serbia'), (155, 'Seychelles'), (156, 'Sierra Leone'), (157, 'Singapore'), (158, 'Slovakia'), (159, 'Slovenia'), (160, 'Solomon Islands'), (161, 'Somalia'), (162, 'South Africa'), (163, 'South Korea'), (164, 'South Sudan'), (165, 'Spain'), (166, 'Sri Lanka'), (167, 'Sudan'), (168, 'Suriname'), (169, 'Sweden'), (170, 'Switzerland'), (171, 'Syria'), (172, 'Tajikistan'), (173, 'Tanzania'), (174, 'Thailand'), (175, 'Timor-Leste'), (176, 'Togo'), (177, 'Tonga'), (178, 'Trinidad and Tobago'), (179, 'Tunisia'), (180, 'Turkey'), (181, 'Turkmenistan'), (182, 'Tuvalu'), (183, 'Uganda'), (184, 'Ukraine'), (185, 'United Arab Emirates'), (186, 'United Kingdom'), (187, 'United States of America'), (188, 'Uruguay'), (189, 'Uzbekistan'), (190, 'Vanuatu'), (191, 'Venezuela'), (192, 'Vietnam'), (193, 'Yemen'), (194, 'Zambia'), (195, 'Zimbabwe')], null=True)),
                ('zip', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
