# Generated by Django 5.1.4 on 2024-12-26 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_profile_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
    ]
