# Generated by Django 4.1.5 on 2024-12-26 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(default='Post', max_length=300)),
                ('catcreate_date', models.DateField(auto_now_add=True)),
                ('catimg', models.ImageField(blank=True, null=True, upload_to='images/catimg')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('body', tinymce.models.HTMLField()),
                ('featured_content', models.CharField(max_length=250)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('catslug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('postscategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='djangoblog.postscategory')),
            ],
            options={
                'ordering': ('-create_date', '-pk'),
            },
        ),
    ]
